"""Start

Revision ID: 525d697cba26
Revises: 
Create Date: 2022-09-09 23:11:17.603246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "525d697cba26"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_account_projection_housekeeping",
        sa.Column(
            "pk", sa.Integer(), server_default="1", autoincrement=False, nullable=False
        ),
        sa.Column("last_seen_logical_time", sa.Integer(), nullable=True),
        sa.Column("last_seen_observed_at", sa.DateTime(), nullable=True),
        sa.Column("observed_event_count", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "bank_accounts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("create sequence events_logical_time")
    op.create_table(
        "events",
        sa.Column("logical_time", sa.Integer(), nullable=False),
        sa.Column(
            "observed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("aggregate_id", sa.String(), nullable=False),
        sa.Column("sequence_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.UniqueConstraint("logical_time"),
    )
    op.create_index(
        op.f("ix_events_aggregate_id"), "events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_events_event_type"), "events", ["event_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_event_type"), table_name="events")
    op.drop_index(op.f("ix_events_aggregate_id"), table_name="events")
    op.drop_table("events")
    op.execute("drop sequence events_logical_time")
    op.drop_table("bank_accounts")
    op.drop_table("bank_account_projection_housekeeping")
    # ### end Alembic commands ###
